name: PR Checks Workflow
on:
  pull_request:
    branches:
      - develop
jobs:
  build_and_check:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          npm install
          npm run build
      - name: Test
        run: |
          npm test
      - name: Code Quality Check
        run: |
          eslint .
